---
- name: Install Helm on all nodes
  hosts: all
  become: true
  tasks:
    - name: Add Helm GPG key
      shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null

    - name: Add Helm repository
      apt_repository:
        repo: deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable-debian

    - name: Install Helm package
      apt:
        name: helm
        state: present
        update_cache: yes

- name: Initialize Control Plane
  hosts: control_plane
  become: true
  tasks:
      
    - name: Initialize Kubernetes control plane
      command: >
        kubeadm init 
        --pod-network-cidr={{ hostvars['all']['vars']['pod_cidr'] }} 
        --control-plane-endpoint={{ ansible_host }}
        --cri-socket /var/run/cri-dockerd.sock
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Untaint control plane node
      command: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-

    - name: Create kube-flannel namespace
      command: kubectl create ns kube-flannel
      ignore_errors: true

    - name: Label kube-flannel namespace
      command: kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged

    - name: Add Flannel helm repo
      command: helm repo add flannel https://flannel-io.github.io/flannel/

    - name: Install Flannel CNI
      command: helm install flannel --set podCidr={{ hostvars['all']['vars']['pod_cidr'] }} --namespace kube-flannel flannel/flannel

- name: Configure Worker Nodes
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups['control_plane'][0]]['kubeadm_init']['stdout_lines'] | select('search', 'kubeadm join') | list | first }}"

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy kubeconfig from control plane
      copy:
        src: "{{ hostvars[groups['control_plane'][0]]['ansible_env']['HOME'] }}/.kube/config"
        dest: $HOME/.kube/config
        mode: '0644'
