---
- name: Install Helm on all nodes
  hosts: all
  become: true
  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Execute Helm installation script
      command: /tmp/get_helm.sh

    - name: Clean up installation script
      file:
        path: /tmp/get_helm.sh
        state: absent

- name: Initialize Control Plane
  hosts: control_plane
  become: true
  tasks:
      
    - name: Initialize Kubernetes control plane
      command: >
        kubeadm init 
        --pod-network-cidr={{ hostvars['all']['vars']['pod_cidr'] }} 
        --control-plane-endpoint={{ ansible_host }}
        --cri-socket /var/run/cri-dockerd.sock
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Untaint control plane node
      command: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-

    - name: Create kube-flannel namespace
      command: kubectl create ns kube-flannel
      ignore_errors: true

    - name: Label kube-flannel namespace
      command: kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged

    - name: Add Flannel helm repo
      command: helm repo add flannel https://flannel-io.github.io/flannel/

    - name: Install Flannel CNI
      command: helm install flannel --set podCidr={{ hostvars['all']['vars']['pod_cidr'] }} --namespace kube-flannel flannel/flannel

- name: Configure Worker Nodes
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups['control_plane'][0]]['kubeadm_init']['stdout_lines'] | select('search', 'kubeadm join') | list | first }}"

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy kubeconfig from control plane
      copy:
        src: "{{ hostvars[groups['control_plane'][0]]['ansible_env']['HOME'] }}/.kube/config"
        dest: $HOME/.kube/config
        mode: '0644'
